project_id = "wytvipaylpumxdmitgqi"

[functions.chat-support]
verify_jwt = false

[functions.viral-suggestions]
verify_jwt = false

[functions.virality-score]
verify_jwt = false

[functions.generate-thumbnail]
verify_jwt = false

[functions.detect-viral-moments]
verify_jwt = false

[functions.voice-profiling]
verify_jwt = false

[functions.product-recognition]
verify_jwt = false

[functions.audio-processor]
verify_jwt = false

[functions.copyright-checker]
verify_jwt = false

[functions.content-moderation]
verify_jwt = false

[functions.audio-transcription]
verify_jwt = false

[functions.translate-subtitles]
verify_jwt = false

[functions.audio-normalization]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.edit-image]
verify_jwt = false
