project_id = "wytvipaylpumxdmitgqi"

[functions.chat-support]
verify_jwt = false

[functions.viral-suggestions]
verify_jwt = false

[functions.virality-score]
verify_jwt = false

[functions.generate-thumbnail]
verify_jwt = false